name: CI — STAGE
on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

env:
  GML_GCP__STAGING_PROJECT_ID: ${{{{ vars.GCP_PROJECT_ID_STAGING }}}}
  GML_TEAM: ${{{{ vars.GML_TEAM }}}}
  GML_PROJECT: ${{{{ vars.GML_PROJECT }}}}

jobs:
  ci-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{{{ secrets.WIF_PROVIDER_STAGING }}}}
          service_account: ${{{{ secrets.SA_EMAIL_STAGING }}}}
      - run: uv sync
      - run: uv run pytest tests/unit/ tests/integration/ -v
      - run: gml deploy dags
      - run: gml deploy features
      - run: gml run --vertex --all --sync
